name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  backend:
    name: Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    env:
      DATABASE_URL: postgresql://user:password@localhost:5432/test
      JWT_SECRET: test-secret
      REFRESH_TOKEN_SECRET: test-refresh-secret
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test -- --runInBand
      - name: Build
        run: npm run build

  frontend:
    name: Frontend
    runs-on: ubuntu-latest
    needs: backend
    defaults:
      run:
        working-directory: frontend
    env:
      VITE_API_URL: http://localhost:3000/api/v1
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Run unit tests
        run: npm run test -- --run
      - name: Build
        run: npm run build
