name: Dependency Review

on:
  pull_request:
    branches: [ master, main ]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Review dependencies for vulnerabilities
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: moderate
          deny-licenses: GPL-1.0,GPL-2.0,GPL-3.0,AGPL-3.0
          comment-summary-in-pr: true